### ISSUE TITLE
Fail to create specific metadata on a clean environment

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#543] opened 2020-05-18 20:47 UTC
On a clean system/environment install Elyra

Try to add a new metadata:
```
elyra-metadata install  runtime-images \
    --schema_name=runtime-image \
    --name=covid-anaconda \
    --display_name="COVID with Anaconda Python 3" \
    --image_name="lresende/anaconda3:latest"
```

Failure:
```
(/Users/some-user/pd/cn-demo/env) some-user@fuzzy:~/pd/cn-demo$ elyra-metadata install  runtime-images \
    --schema_name=runtime-image \
    --name=covid-anaconda \
    --display_name="COVID with Anaconda Python 3" \
    --image_name="lresende/anaconda3:latest"
The following exception occurred saving metadata instance 'covid-anaconda' for schema 'runtime-image': [Errno 2] No such file or directory: '/Users/some-user/Library/Jupyter/metadata/runtime-images/covid-anaconda.json'
Install a metadata instance into namespace 'runtime-images'.
Options
-------
--replace
	Replace existing instance
--schema_name=<string>
	The schema_name of the metadata instance to install
--name=<string>
	The name of the metadata instance to install
--display_name=<string>
	The display name of the Runtime Image; pattern: ^[a-zA-Z][a-zA-Z0-9-_. (){}]*[a-zA-Z0-9)}]$
--image_name=<string>
	Runtime Image description
(/Users/some-user/pd/cn-demo/env) some-user@fuzzy:~/pd/cn-demo$ 
```

Workaround before executing the command again:
```
mkdir -p /Users/some-user/Library/Jupyter/metadata/runtime-images/
```

**Comment by kevin-bates** [comment] 2020-05-18 21:11
This is fixed in #539.  The issue is that the namespace "does exist", just not in the user area.  I had addressed this in one of the earlier commits of #539.
```
~/repos/oss/elyra-ai/elyra (metadata-writes)$ rm -rf /Users/kbates/Library/Jupyter/metadata/runtime-images
~/repos/oss/elyra-ai/elyra (metadata-writes)$ elyra-metadata install  runtime-images \
    --schema_name=runtime-image \
    --name=covid-anaconda \
    --display_name="COVID with Anaconda Python 3" \
    --image_name="lresende/anaconda3:latest"
Metadata instance 'covid-anaconda' for schema 'runtime-image' has been written to: /Users/kbates/Library/Jupyter/metadata/runtime-images/covid-anaconda.json
```

**Closed** 2020-05-19 18:31 UTC
Labels: component:metadata, priority:high
