### ISSUE TITLE
Add ability to run pipeline locally as a series of interconnected notebooks

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#579] opened 2020-05-28 18:44 UTC
without the use of kubeflow or other pipeline runtimes

**Comment by lresende** [comment] 2020-07-01 15:36
I believe that this would only be viable for small notebooks, and we consider enterprise scenarios or even medium AI models the `local notebook resources` are not going to be enough. The other problem is how to handle isolation required, particularly when you have nodes that require different frameworks (e.g. TensorFlow, pandas, etc). If we have to handle all of that, we would then be on the `AI Platform` business and have to reimplement a lot of things that are already available today in Kubeflow, Airflow, etc. 

For now, my inclination is to avoid spending too much time on this area.

**Comment by lresende** [comment] 2020-11-10 19:00
This is actually a duplicate of #842 and has been implemented as part of #845

**Closed by lresende** 2020-11-10 19:00 UTC
Labels: duplicate, kind:investigative
