### ISSUE TITLE
Should packages to install be optional in papermill run notebooks kfp component

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1966] opened 2021-07-27 12:40 UTC
**Describe the issue**
Should packages to install be optional in papermill run notebooks kfp component. 
The question we should ask is, do we always require a package to be installed in order to run a notebook?

![image](https://user-images.githubusercontent.com/382917/127155161-73ac2e46-13b3-42a9-8e13-dffc81fae2e3.png)

**Comment by ptitzler** [comment] 2021-07-27 13:40
also see https://github.com/elyra-ai/elyra/issues/1956, which would set a default of `[]` instead of making this property optional

**Comment by akchinSTC** [comment] 2021-07-27 16:16
Closing due to duplicate of #1956

**Closed by akchinSTC** 2021-07-27 16:16 UTC
Labels: component:pipeline-editor, component:pipeline-runtime
