### ISSUE TITLE
Synchronize the list of docker images between Submit Notebook and Submit Pipeline

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#360] opened 2020-03-12 22:28 UTC
Submit Notebook:
![image](https://user-images.githubusercontent.com/382917/76571910-e38f6c00-6475-11ea-8f8f-f349d0ea5367.png)

Submit pipeline:
![image](https://user-images.githubusercontent.com/382917/76571963-fefa7700-6475-11ea-96b0-65e90965ac75.png)

**Comment by ajbozarth** [comment] 2020-03-13 18:27
Some notes on our current implementation:

The submit dropdown is hard-coded in one string on line 184 in `SubmitNotebook.ts` but the value (`framework`) is never used and instead the docker image is hardcoded in `generateNotebookPipeline()` in `utils.ts` to `tensorflow/tensorflow:1.12.3-py3`

Note that the pipeline editor docker image list is "hard-coded" in `properties.json`

**Comment by kevin-bates** [comment] 2020-03-13 18:37
Not sure if this came up in the scrum, but should these be hard-coded at all?  I'm wondering if these should be a function of the metadata instance since I would imagine the image to use is a function of the runtime metadata.

**Comment by akchinSTC** [comment] 2020-03-13 19:15
it did come up during the scrum, suggestion from luciano was to have a react component of a sorts, to provide a the same list of images to both items

**Comment by kevin-bates** [comment] 2020-03-13 20:19
But where does that component get the image names from?  Are these "factory" images or will users be able to "BYO"?

**Comment by ajbozarth** [comment] 2020-03-13 20:42
Based on a conversation with @lresende last year when I was writing the pipeline properties code we will have a set of images that we support that we will update from time to time. Thus a "hard-coded" list. I believe what we want to address with this issue is twofold:

1. Fix the fact that `notebook-scheduler` not only has a vague list of images, but also doesn't actually use the user's choice anyway.
2. Create a util to handle the image list, ie some sort of component that both packages "ask" for the list they are to use.

The first one is a bug and could be fixed relatively easily, but the second is not as simple.
We would most likely still have the list hard-coded in the utility component, but it would instead be in the application package. 

Given the obvious bug here in `notebook-scheduler` I would either suggest a quick hard-coded bug fix for this sprint with a followup issue to add the util component, or for this to be a top priority enhancement and make creating the util part of this sprint. Either way I can handle this, but if we take the second path forward I will most likely need to push a few of my issues into next sprint.

@lresende  what's your opinion?

**Comment by kevin-bates** [comment] 2020-03-13 20:53
I'm just trying to understand.  If the hard-coded list is "as-designed", that seems fine provided we don't intend to let others bring their own images, etc.  What we need to avoid is having to cut a new release just to add/remove an image from the list - irrespective of if the set if "factory only" or not.

I agree that the two consumers need to get the set of images from the same source.

Since it appears that both consumers are referencing runtime metadata, I'm a little curious why these weren't part of that, especially considering that facility is already user-extensible (by design).

**Comment by ajbozarth** [comment] 2020-03-13 21:37
I think I see where you're coming from. Let's discuss this in detail at scrum Monday and I'll start working on it Monday based on whatever decisions we make there.

**Comment by lresende** [comment] 2020-03-13 22:07
> * Fix the fact that `notebook-scheduler` not only has a vague list of images, but also doesn't actually use the user's choice anyway.
> 

Yes, fix the bug...

> * Create a util to handle the image list, ie some sort of component that both packages "ask" for the list they are to use.

I would love to see better reutilization of UI components, as well as backend services components, and this seems to be what we are suggesting here:
  - A common widget to display a list of available TensorFlow images
  - If we want to enable users to add their own set of images, we then could expose the supported list of images from the metadata services (e.g. ,metadata/images)

**Comment by kevin-bates** [comment] 2020-03-13 22:18
Thanks for the response @lresende.  Is the reason not to add an images field (list-valued) to the runtime metadata?  Just thinking that these would be closely tied to the platform (kfp, airflow), but if images are "platform-agnostic", then I suppose we'd need to look into adding another namespace type (which  triggers lots of repetitive things so we need to be sure that's what we want to do).

**Closed** 2020-03-20 18:41 UTC
Labels: area:front-end, component:pipeline-editor, component:submit-notebook-button, kind:bug
