### ISSUE TITLE
Enhance support for docker image versioning 

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#497] opened 2020-05-05 17:09 UTC
Currently, we are storing on the pipeline the full docker image `pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime` but, while the image name is constant `pytorch/pytorch` the version tag `1.2-cuda10.0-cudnn7-runtime` is not and will make the subsequent tag/version update cause issues with existing saved pipelines. 

We should split the information about the image name and image tag, and store only the image name, but use the full info when submitting which will enable backward compatibility while using the latest configured version.

Note that we should also think about image version compatibility, and how a user could force to run on an old version, but I think this can be resolved with the notion of `bring your own image` functionality being added by #462

**Comment by kevin-bates** [comment] 2020-07-21 21:32
I think rather than split the tag off the image, we should simply reference the _name_ of the runtime-image instance since that is the canonical identifier of that metadata instance.  Otherwise, we can't necessarily equate an image to the appropriate tag since multiple metadata instances could be referencing the same image name, but with different tags.  So then the name of the runtime-image instance becomes the abstraction/level-of-indirection that is desired.

Note: this approach could lead to reproducibility issues since the pipeline will be using a different image on its "next run" (after the runtime-image instance is updated), whereas the current approach **always** uses the same image.  The issue then becomes, should a user have to update all pipelines if they want to switch to an updated image?  That's the trade-off.

> Note that we should also think about image version compatibility, and how a user could force to run on an old version, but I think this can be resolved with the notion of bring your own image functionality being added by #462

Agreed.  If they were using runtime-image `foo`, which equated to a docker image:tag of `tensorflow/tensorflow:1.12.0-gpu-py3`, then decided to update instance `foo` such that image:tag became `tensorflow/tensorflow:2.2.0-gpu-py3`, their existing pipelines that referenced `foo` would use the updated image.  So, to force the use of the previous image, they would need to do the following:
- Create a new runtime-image instance (e.g., `foo-1.12.0`) 
- Update the appropriate pipelines in which they desire the previous behavior to use runtime-image instance `foo-1.12.0`

Necessary changes:
- Frontend:
  - needs to store the runtime-image name instead of its `image_name` field value
  - should validate that name is an existing image name since runtime-image instances can be removed
- Backend:
  - needs to lookup runtime-image name and raise an exception if not found, then use the `image_name` value where applicable
- Migration Utility:
  - needs to locate the referenced `image_name` value within the fields of the existing runtime-image instances and replace its value with the located name.  If it cannot locate the `image_name` value currently in the pipeline, it will need to leave the field empty - so that the pipeline node is flagged as in error and the user can apply the proper image.

@lresende - does that sound right?

**Comment by kevin-bates** [comment] 2020-07-22 00:53
> Note: this approach could lead to reproducibility issues since the pipeline will be using a different image on its "next run" (after the runtime-image instance is updated), whereas the current approach always uses the same image. The issue then becomes, should a user have to update all pipelines if they want to switch to an updated image? That's the trade-off.

After discussing with @lresende, we decided to leave things as-is and err on side of reproducibility since that's more important.  If users update the images in existing runtime-image instances, they will need to update the appropriate nodes of existing pipelines to use the updated image by editing the node.

Closing this issue and will re-open should this warrant a revisit.

**Closed by kevin-bates** 2020-07-22 00:53 UTC
Labels: component:pipeline-editor, component:pipeline-runtime, status:Needs Discussion
