### ISSUE TITLE
pipelines: [local] file dependencies are treated as optional input

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#674] opened 2020-06-23 21:59 UTC
Recreate:
- 1.0.0 Beta
- Create a pipeline
- add a[ny] notebook, defining a file dependency that does not exist
- export or run the pipeline

![image](https://user-images.githubusercontent.com/13068832/85467824-891ba680-b560-11ea-9055-12367030f1f1.png)

Observed outcome:
- The pipeline is processed successfully (if the referenced file is not used in the notebook) or fails during execution due to 404. 

Expected outcome:
 - An error is raised before the pipeline can be processed in any form, e.g. is submitted to kfp or exported to a Kubeflow yaml spec file or Python program. 

If this is working as designed we should update the documentation to indicate that this is an optional dependency that is not enforced.

**Comment by kevin-bates** [comment] 2020-06-30 17:31
This is a duplicate of #204

**Closed by kevin-bates** 2020-06-30 17:31 UTC
Labels: duplicate
