### ISSUE TITLE
"latest" tags for docker images are not actually latest

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2455] opened 2022-02-08 04:04 UTC
Currently, our "latest" tags on Dockerhub are not aliases for the latest releases:

- https://hub.docker.com/r/elyra/elyra/tags
- https://hub.docker.com/r/elyra/kf-notebook/tags

**Comment by kevin-bates** [comment] 2022-02-08 15:10
Looks like the `latest` tag has been getting maintained.  I just pulled the 3.5.3 images and updated/pushed with a latest tag.

**Comment by kevin-bates** [comment] 2022-02-08 15:11
We'll need to make a note to keep maintaining `latest` or remove the images.

Closing this issue for now.

**Comment by ptitzler** [comment] 2022-02-08 15:33
> We'll need to make a note to keep maintaining `latest` or remove the images.

For reference: https://elyra.readthedocs.io/en/latest/developer_guide/release.html#publish-the-release

**Comment by thesuperzapper** [comment] 2022-02-09 06:53
> Looks like the `latest` tag has been getting maintained. I just pulled the 3.5.3 images and updated/pushed with a latest tag.

@kevin-bates I believe you missed the `elyra/eylra` image, because when I run `docker run -it --entrypoint /bin/bash elyra/elyra:latest`, and then run `pip list | grep elyra`, I see that elyra `3.2.1` is installed.

**Comment by ptitzler** [comment] 2022-02-09 18:13
I confirmed:
 - The digests for `elyra/elyra:latest` and `elyra/elyra:3.6.0` now match on dockerhub: `sha256:8ce7089a34af05ff0ff55afbe255b446af10c6c61d037a243f79403cf9fb15d9`
 - The digests for `elyra/kf-notebook:latest` and `elyra/kf-notebook:3.6.0` now match on dockerhub: `sha256:d59b79d1a7fd113f47e5bb9effbd413536455ab3133819d1046ab60f0c96ac3c`

The corresponding 3.6.0 images on quay.io are also properly tagged as `latest`.

**Closed by ptitzler** 2022-02-09 18:13 UTC
Labels: component:install
