### ISSUE TITLE
Run pipeline: unexpected end of JSON input

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1929] opened 2021-07-16 18:16 UTC
**Describe the issue**

![image](https://user-images.githubusercontent.com/13068832/125990989-4ef31f23-fd9c-4d43-a1ed-ef2185269e3c.png)

**To Reproduce**
1. Create RTC with KFP endpoint that has an invalid port (for example)
2. Create pipeline
3. Run pipeline

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 93, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 111, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 104, in process
        api_password)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 585, in _get_user_auth_session_cookie
        get_response = requests.get(url)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/requests/api.py", line 75, in get
        return request('get', url, params=params, **kwargs)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/requests/api.py", line 61, in request
        return session.request(method=method, url=url, **kwargs)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='cloning1.fyre.ibm.com', port=31380): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0752ec990>: Failed to establish a new connection: [Errno 61] Connection refused'))
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0/master

**Comment by marthacryan** [comment] 2021-07-27 18:12
What would be a better message? The issue here is that the server is sending an empty string, so the function parsing the response is throwing an error. The status code is 500, which is "Internal Server Error". The issue is coming up when it times out making the request. @kevin-bates Do you know if that's the correct code?

**Comment by kevin-bates** [comment] 2021-07-27 19:07
This is the correct status code (500) for what is happening in the server which is that the server is not properly handling exceptions within the pipeline framework.  As a result, I suspect the exception handling plumbing baked into the web handler stack gets confused - leading to a misleading JSON parse error.

At a minimum, this block: https://github.com/elyra-ai/elyra/blob/f85c753209807b6a47c0b5cd582f61a158991807/elyra/pipeline/processor_kfp.py#L148-L154

could catch `requests.exceptions.ConnectionError` and handle it exactly like `MaxRetryError`.

However, I would also recommend that the pipeline handlers be extended similar to what the metadata handlers are doing: https://github.com/elyra-ai/elyra/blob/f85c753209807b6a47c0b5cd582f61a158991807/elyra/metadata/handlers.py#L64-L71
so that there's finer control over mapping errors to status codes.  I'm sure it's the case today, given their absence, that all pipeline-related errors are returning `500` status codes - which isn't necessarily incorrect, but I suspect there are occasions where a `4xx` code may be more applicable.

**Comment by marthacryan** [comment] 2021-07-27 19:26
@kevin-bates Oh ok so this should be a backend change then? @akchinSTC @kiersten-stokes

**Comment by kevin-bates** [comment] 2021-07-27 22:56
Yes.  Since I wasn't able to troubleshoot this using my IDE I just went ahead with the first suggestion of extending the try/catch block with `requests.exceptions.ConnectionError` and now get this:
![image](https://user-images.githubusercontent.com/22599560/127237797-ac13edcd-caa0-4ae0-bceb-bbff75769e4e.png)

I'll submit a fix for this.  The handler updates, while recommended, are not necessarily necessary at this time, but any other unhandled exception will result in the same JSON decode dialog and those kinds of updates would likely catch rogue occurrences.

**Comment by ptitzler** [comment] 2021-07-28 22:04
I do think the front-end should be fixed too because there are potentially other problem 
scenarios that would trigger a server response that is not JSON formatted.

**Closed** 2021-07-30 01:58 UTC
Labels: component:pipeline-editor 2.0, kind:bug
