### ISSUE TITLE
Dialogs are non-modal

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#435] opened 2020-04-23 12:00 UTC
When submitting pipelines, the resulting dialogs are non-modal. e.g. if you have a slow internet connection, you and click multiple times, a queue of the same dialogs builds up and you loose state where you actually are in the submission process

**Comment by romeokienzler** [comment] 2021-01-29 09:35
Just noticed this again - I was thinking the pipeline is still submitting but I had a network issue and only saw the "underlying" dialog once I've closed the previous one.
I suggest not waiting for an upstream fix in jupyterlab but moving those outputs to the status panel

**Comment by ptitzler** [comment] 2021-01-29 15:37
One problem with modal dialogs is that they prevent the user from doing anything else. In some scenarios this would be a major issue, e.g. when a pipeline is executed locally, which might take a long time.

**Comment by romeokienzler** [comment] 2021-01-30 16:54
agree, that's why I suggested:

>I suggest not waiting for an upstream fix in jupyterlab but moving those outputs to the status panel

Do you know if this is possible?

**Comment by lresende** [comment] 2021-02-01 15:22
Duplicate of #1064

**Closed by lresende** 2021-02-01 15:22 UTC
Labels: area:front-end, duplicate, upstream
