### ISSUE TITLE
submit notebook - deep learning framework Pandas failed with KeyError: 'kernel_manager_class'

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#619] opened 2020-06-09 00:05 UTC
Recreate:
 - Install rc2 + configure kfp
 - Create a 1-cell notebook (`print('Hello world')` - see next comment for attached sample file
 - Choose `Pandas` as DLF

The job fails but works with another kernel I selected randomly. 

Log output:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  7572  100  7572    0     0  30780      0 --:--:-- --:--:-- --:--:-- 31032
Collecting papermill
  Downloading 
https://files.pythonhosted.org/packages/ed/70/69799316f1b92bc3518f1bbb71a8aaa2406e05ef73f15edf2b98fc23901c/papermill-2.1.1-py3-none-any.whl
Collecting click (from papermill)
  Downloading 
https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
 (82kB)
Requirement already satisfied, skipping upgrade: nbformat in /usr/local/lib/python3.7/site-packages (from papermill) (4.4.0)
Requirement already satisfied, skipping upgrade: entrypoints in /usr/local/lib/python3.7/site-packages (from papermill) (0.3)
Collecting tqdm>=4.32.2 (from papermill)
  Downloading 
https://files.pythonhosted.org/packages/f3/76/4697ce203a3d42b2ead61127b35e5fcc26bba9a35c03b32a2bd342a4c869/tqdm-4.46.1-py2.py3-none-any.whl
 (63kB)
Collecting tenacity (from papermill)
  Downloading 
https://files.pythonhosted.org/packages/b5/05/ff089032442058bd3386f9cd991cd88ccac81dca1494d78751621ee35e62/tenacity-6.2.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: jupyter-client in /usr/local/lib/python3.7/site-packages (from papermill) (5.3.1)
Collecting nbclient>=0.2.0 (from papermill)
  Downloading 
https://files.pythonhosted.org/packages/e7/d8/65dac094885423b6a8e8c4e2071f980c81deecf0a66e70eed591c617402d/nbclient-0.3.1-py3-none-any.whl
 (70kB)
Collecting black (from papermill)
  Downloading 
https://files.pythonhosted.org/packages/fd/bb/ad34bbc93d1bea3de086d7c59e528d4a503ac8fe318bd1fa48605584c3d2/black-19.10b0-py36-none-any.whl
 (97kB)
Collecting ansiwrap (from papermill)
  Downloading 
https://files.pythonhosted.org/packages/03/50/43e775a63e0d632d9be3b3fa1c9b2cbaf3b7870d203655710a3426f47c26/ansiwrap-0.8.4-py2.py3-none-any.whl
Collecting requests (from papermill)
  Downloading 
https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
 (58kB)
Collecting pyyaml (from papermill)
  Downloading 
https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz
 (269kB)
Requirement already satisfied, skipping upgrade: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/site-packages (from nbformat->papermill) (3.0.2)
Requirement already satisfied, skipping upgrade: jupyter-core in /usr/local/lib/python3.7/site-packages (from nbformat->papermill) (4.5.0)
Requirement already satisfied, skipping upgrade: ipython-genutils in /usr/local/lib/python3.7/site-packages (from nbformat->papermill) (0.2.0)
Requirement already satisfied, skipping upgrade: traitlets>=4.1 in /usr/local/lib/python3.7/site-packages (from nbformat->papermill) (4.3.2)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /usr/local/lib/python3.7/site-packages (from tenacity->papermill) (1.12.0)
Requirement already satisfied, skipping upgrade: pyzmq>=13 in /usr/local/lib/python3.7/site-packages (from jupyter-client->papermill) (18.0.2)
Requirement already satisfied, skipping upgrade: tornado>=4.1 in /usr/local/lib/python3.7/site-packages (from jupyter-client->papermill) (6.0.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /usr/local/lib/python3.7/site-packages (from jupyter-client->papermill) (2.8.0)
Collecting async-generator (from nbclient>=0.2.0->papermill)
  Downloading 
https://files.pythonhosted.org/packages/71/52/39d20e03abd0ac9159c162ec24b93fbcaa111e8400308f2465432495ca2b/async_generator-1.10-py3-none-any.whl
Collecting nest-asyncio (from nbclient>=0.2.0->papermill)
  Downloading 
https://files.pythonhosted.org/packages/74/b4/b24e0a271fb78990c2c62238321686454824b1357ce7abcf20f431fd903d/nest_asyncio-1.3.3-py3-none-any.whl
Requirement already satisfied, skipping upgrade: attrs>=18.1.0 in /usr/local/lib/python3.7/site-packages (from black->papermill) (19.1.0)
Collecting toml>=0.9.4 (from black->papermill)
  Downloading 
https://files.pythonhosted.org/packages/9f/e1/1b40b80f2e1663a6b9f497123c11d7d988c0919abbf3c3f2688e448c5363/toml-0.10.1-py2.py3-none-any.whl
Collecting pathspec<1,>=0.6 (from black->papermill)
  Downloading 
https://files.pythonhosted.org/packages/5d/d0/887c58853bd4b6ffc7aa9cdba4fc57d7b979b45888a6bd47e4568e1cf868/pathspec-0.8.0-py2.py3-none-any.whl
Collecting appdirs (from black->papermill)
  Downloading 
https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Collecting typed-ast>=1.4.0 (from black->papermill)
  Downloading 
https://files.pythonhosted.org/packages/5d/10/0c1e8aa723a2b0c4032e048d8e511df82c8a1262f0e1df5e4c54eb2613e9/typed_ast-1.4.1-cp37-cp37m-manylinux1_x86_64.whl
 (737kB)
Collecting regex (from black->papermill)
  Downloading 
https://files.pythonhosted.org/packages/84/60/cd50cc641bc3199bce3d37b3d240c20af9447ee06c8c283def56d7914232/regex-2020.6.8-cp37-cp37m-manylinux2010_x86_64.whl
 (661kB)
Collecting textwrap3>=0.9.2 (from ansiwrap->papermill)
  Downloading 
https://files.pythonhosted.org/packages/77/9c/a53e561d496ee5866bbeea4d3a850b3b545ed854f8a21007c1e0d872e94d/textwrap3-0.9.2-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->papermill)
  Downloading 
https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl
 (126kB)
Collecting idna<3,>=2.5 (from requests->papermill)
  Downloading 
https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
 (58kB)
Collecting chardet<4,>=3.0.2 (from requests->papermill)
  Downloading 
https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
 (133kB)
Collecting certifi>=2017.4.17 (from requests->papermill)
  Downloading 
https://files.pythonhosted.org/packages/98/99/def511020aa8f663d4a2cfaa38467539e864799289ff354569e339e375b1/certifi-2020.4.5.2-py2.py3-none-any.whl
 (157kB)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in /usr/local/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->papermill) (0.15.4)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->papermill) (41.0.1)
Requirement already satisfied, skipping upgrade: decorator in /usr/local/lib/python3.7/site-packages (from traitlets>=4.1->nbformat->papermill) (4.4.0)
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (setup.py): started
  Building wheel for pyyaml (setup.py): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp37-cp37m-linux_x86_64.whl size=471268 sha256=7158f6e3590ba6b866d3156841096723ae62e52b80e144dc26acaa8d136618c8
  Stored in directory: /root/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd
Successfully built pyyaml
ERROR: nbclient 0.3.1 has requirement jupyter-client>=6.1.0, but you'll have jupyter-client 5.3.1 which is incompatible.
ERROR: nbclient 0.3.1 has requirement nbformat>=5.0, but you'll have nbformat 4.4.0 which is incompatible.
Installing collected packages: click, tqdm, tenacity, async-generator, nest-asyncio, nbclient, toml, pathspec, appdirs, typed-ast, regex, black, textwrap3, ansiwrap, urllib3, idna, chardet, certifi, requests, pyyaml, papermill
Successfully installed ansiwrap-0.8.4 appdirs-1.4.4 async-generator-1.10 black-19.10b0 certifi-2020.4.5.2 chardet-3.0.4 click-7.1.2 idna-2.9 nbclient-0.3.1 nest-asyncio-1.3.3 papermill-2.1.1 pathspec-0.8.0 pyyaml-5.3.1 regex-2020.6.8 requests-2.23.0 tenacity-6.2.0 textwrap3-0.9.2 toml-0.10.1 tqdm-4.46.1 typed-ast-1.4.1 urllib3-1.25.9
WARNING: You are using pip version 19.2.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting minio
  Downloading 
https://files.pythonhosted.org/packages/aa/60/81f4a1dc2d320832840288d7ec88aa3e4ee495d8f1452b4c79d8bd67136b/minio-5.0.10-py2.py3-none-any.whl
 (75kB)
Requirement already satisfied, skipping upgrade: urllib3 in /usr/local/lib/python3.7/site-packages (from minio) (1.25.9)
Collecting configparser (from minio)
  Downloading 
https://files.pythonhosted.org/packages/4b/6b/01baa293090240cf0562cc5eccb69c6f5006282127f2b846fad011305c79/configparser-5.0.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: python-dateutil in /usr/local/lib/python3.7/site-packages (from minio) (2.8.0)
Requirement already satisfied, skipping upgrade: pytz in /usr/local/lib/python3.7/site-packages (from minio) (2019.2)
Requirement already satisfied, skipping upgrade: certifi in /usr/local/lib/python3.7/site-packages (from minio) (2020.4.5.2)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil->minio) (1.12.0)
Installing collected packages: configparser, minio
Successfully installed configparser-5.0.0 minio-5.0.10
WARNING: You are using pip version 19.2.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tar: Removing leading `/' from member names
/
Untitled.ipynb
getting_started_python.py
Updating package papermill
Updating package minio
Imports Complete.....
Parsing Arguments.....
Get file Untitled-0a32af42-aa87-4268-9e70-155afd23391e.tar.gz from bucket ptitzler
Processing dependencies........
TAR Archive pulled from Object Storage.
Unpacking........
Unpacking Complete.
Executing notebook through Papermill: Untitled.ipynb ==> Untitled-output.ipynb
Unexpected error: <class 'ImportError'>
Converting from ipynb to html....
Uploading Errored Notebook back to Object Storage
Uploading file Untitled-output.ipynb as Untitled.ipynb to bucket ptitzler
Uploading file Untitled.html as Untitled.html to bucket ptitzler

Executing: 0cell [00:00, ?cell/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'kernel_manager_class'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "bootstrapper.py", line 168, in <module>
    kernel_name="python3"
  File "/usr/local/lib/python3.7/site-packages/papermill/execute.py", line 106, in execute_notebook
    **engine_kwargs
  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/usr/local/lib/python3.7/site-packages/papermill/clientwrap.py", line 36, in execute
    with self.setup_kernel(**kwargs):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 419, in setup_kernel
    self.start_kernel_manager()
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 327, in start_kernel_manager
    self.km = self.kernel_manager_class(kernel_name=self.kernel_name, config=self.config)
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 240, in _kernel_manager_class_default
    from jupyter_client import AsyncKernelManager
ImportError: cannot import name 'AsyncKernelManager' from 'jupyter_client' (/usr/local/lib/python3.7/site-packages/jupyter_client/__init__.py)

Executing: 0cell [00:00, ?cell/s]
```

**Comment by ptitzler** [comment] 2020-06-09 00:09
Compressed notebook, which can't be attached as `.ipynb` file

[Untitled.ipynb.zip](https://github.com/elyra-ai/elyra/files/4749169/Untitled.ipynb.zip)

**Comment by kevin-bates** [comment] 2020-06-09 00:20
I believe this will be addressed by https://github.com/elyra-ai/kfp-notebook/pull/28.  The issue is that nbclient needs a more current version of jupyter_client than what papermill installs and this is reflected above:
```
ERROR: nbclient 0.3.1 has requirement jupyter-client>=6.1.0, but you'll have jupyter-client 5.3.1 which is incompatible.
```

**Comment by akchinSTC** [comment] 2020-06-15 17:39
Resolved with merge of https://github.com/elyra-ai/kfp-notebook/pull/28

**Closed by akchinSTC** 2020-06-15 17:39 UTC
Labels: component:pipeline-runtime, kind:bug
