### ISSUE TITLE
Investigate ways to improve how critical notebook failures can be surfaced more easily

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#951] opened 2020-10-02 18:37 UTC
Scenario:
- Clone the Elyra examples repository https://github.com/elyra-ai/examples
- Open JL and navigate to `pipelines/dax_noaa_weather_data`
- Open  `analyze_NOAA_weather_data.pipeline`
- Open the properties for the `load_data.ipynb` node
- Remove the pre-defined environment variable `DATASET_URL`
- Save and run the pipeline using the local configuration
- Pipeline execution will fail because the notebook cannot perform it's task without the variable being present (code cell 2)

**Comment by ptitzler** [comment] 2020-10-02 19:33
The following information is displayed in

![image](https://user-images.githubusercontent.com/13068832/94962145-d6d27400-04aa-11eb-8dcf-50ead0107789.png)

```
Traceback (most recent call last):
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 151, in process
    subprocess.run(argv, cwd=file_dir, env=envs, check=True)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['papermill', '/Users/patti/elyra_ga/workspace_italo/hello_world/load_data.ipynb', '/Users/patti/elyra_ga/workspace_italo/hello_world/load_data.ipynb', '--cwd', '/Users/patti/elyra_ga/workspace_italo/hello_world']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 70, in process
    operation_processor.process(operation)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 154, in process
    raise RuntimeError(f'Internal error executing {filepath}') from ex
RuntimeError: Internal error executing /Users/patti/elyra_ga/workspace_italo/hello_world/load_data.ipynb

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 89, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 69, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 72, in process
    raise RuntimeError(f'Error processing operation {operation.name}.') from ex
RuntimeError: Error processing operation load_data.
```

The following information is included in the log file, when running the pipeline locally. Note the output in `Exception encountered at "In [2]":`, which surfaces the root cause of the expected failure.

```
Processing Pipeline : sss
Input Notebook:  /Users/patti/elyra_ga/workspace_italo/hello_world/load_data.ipynb
Output Notebook: /Users/patti/elyra_ga/workspace_italo/hello_world/load_data.ipynb
Working directory: /Users/patti/elyra_ga/workspace_italo/hello_world
Executing:   0%|                                                               | 0/11 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:  36%|████████████████████                                   | 4/11 [00:01<00:02,  2.70cell/s]
Traceback (most recent call last):
  File "/Users/patti/anaconda3/envs/elyra_ga/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/papermill/cli.py", line 256, in papermill
    execution_timeout=execution_timeout,
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/papermill/execute.py", line 110, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/papermill/execute.py", line 222, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [2]":
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-55cb24574a79> in <module>
      1 if os.environ.get('DATASET_URL') is None:
----> 2     raise RuntimeError('Cannot run notebook. Required parameter is missing.')
      3 
      4 data_file = os.environ['DATASET_URL']

RuntimeError: Cannot run notebook. Required parameter is missing.

[E 12:27:42.003 LabApp] Internal error executing /Users/patti/elyra_ga/workspace_italo/hello_world/load_data.ipynb
[E 12:27:42.004 LabApp] Uncaught exception POST /elyra/pipeline/schedule?1601666859941 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/elyra/pipeline/schedule?1601666859941', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 151, in process
        subprocess.run(argv, cwd=file_dir, env=envs, check=True)
      File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['papermill', '/Users/patti/elyra_ga/workspace_italo/hello_world/load_data.ipynb', '/Users/patti/elyra_ga/workspace_italo/hello_world/load_data.ipynb', '--cwd', '/Users/patti/elyra_ga/workspace_italo/hello_world']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 70, in process
        operation_processor.process(operation)
      File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 154, in process
        raise RuntimeError(f'Internal error executing {filepath}') from ex
    RuntimeError: Internal error executing /Users/patti/elyra_ga/workspace_italo/hello_world/load_data.ipynb
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 89, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 69, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/patti/anaconda3/envs/elyra_ga/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 72, in process
        raise RuntimeError(f'Error processing operation {operation.name}.') from ex
    RuntimeError: Error processing operation load_data.
[E 12:27:42.014 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "1575",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
      "X-Xsrftoken": "2|a9adb8bb|0fd98202a8b5a025f542eed9abdc80eb|1600702626",
      "Authorization": "token 248bd113da8cb22fbcada8e1d6738672858b8171b9c9ee7a",
      "Content-Type": "text/plain;charset=UTF-8",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab/workspaces/auto-V",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,de;q=0.8",
      "Cookie": "username-localhost-8889=\"2|1:0|10:1600383050|23:username-localhost-8889|44:MDU2OTMwN2ZkYjgyNDVkZTk4ZjAzOTA0NDM3YjgwMDE=|d3c5c9c627c74545b1fe3f7819e9b6bd1fa6ad2e3b140963bb1e07bfd1d47f79\"; _xsrf=2|a9adb8bb|0fd98202a8b5a025f542eed9abdc80eb|1600702626; username-localhost-8888=\"2|1:0|10:1601666854|23:username-localhost-8888|44:M2I1YWFiZDAwMmJlNGFjNDg1OWFiYWNjZGM3NmFhN2I=|472a3b969ca642d90dfaa058cdd00b960ef40b0b041a7b0cc2971ccba3d05478\""
    }
[E 12:27:42.014 LabApp] 500 POST /elyra/pipeline/schedule?1601666859941 (::1) 2070.48ms referer=http://localhost:8888/lab/workspaces/auto-V
```

The key idea the notebook is trying to implement is that under certain circumstances notebook processing must be aborted, either because a user error (like in this case a missing input), or because the code itself was bad.

**Comment by ptitzler** [comment] 2020-10-02 19:37
Ideally a user won't have to dig through lengthy log outputs to determine where the failure occurred. Do note that the completed notebook (for local execution!) contains the error

![image](https://user-images.githubusercontent.com/13068832/94962762-d38bb800-04ab-11eb-9aa5-88597dc04380.png)

For KFP execution one would have to download the artifacts from COS to obtain the same information.

**Comment by kevin-bates** [comment] 2020-10-02 20:21
Hmm - I'm not convinced we can do much better here.  We might be able to "move" the location of the notebook error closer to the end of the traceback, but given its logged in the first place, that seems sufficient.

In addition, you certainly cannot beat the fact that the error is preserved in the output notebook!  Sure, for non-local runs that output notebook is not local, but that's all working as designed.  

I'm inclined to close this issue but we should probably see what dumping [`CalledProcessError.stderr`](https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError) can do for us.  If it merely leads to the same information getting logged twice, then that is even worse.

**Comment by kevin-bates** [comment] 2020-10-04 15:29
I spent some time with this and there might be _some_ things we can do to prevent the user from having to dig through the server log - although nothing is really easier than just pulling up the notebook and seeing the errors.

1. I think we should be calling `papermill`, both locally and from kfp-notebook, with the `--no-progress-bar` option.  This eliminates the useless progress bar output in the log.  Here's an example of what gets _removed_: 
    `Executing:   0%|          | 0/2 [00:00<?, ?cell/s]Executing notebook with kernel: python3\n\rExecuting:  50%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88     | 1/2 [00:01<00:01,  1.28s/cell]\rExecuting: 100%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88| 2/2 [00:01<00:00,  1.19cell/s]`
2. By adding `capture_output=True` to the `subprocess.run()` command, the resulting `CalledProcessError` instance (raised when a non-zero exit status occurs) will populate its `stderr` property with what is typically in the log file relative to the notebook.  However, this has newlines escaped and the entire stack trace - for the notebook error is on a single line.

    Here's an example:
    `b'Input Notebook:  /Users/kbates/notebooks/elyra/pipeline1/node1.ipynb\nOutput Notebook: /Users/kbates/notebooks/elyra/pipeline1/node1.ipynb\nWorking directory: /Users/kbates/notebooks/elyra/pipeline1\nExecuting notebook with kernel: python3\nTraceback (most recent call last):\n  File "/opt/anaconda3/envs/elyra-dev/bin/papermill", line 10, in <module>\n    sys.exit(papermill())\n  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/click/core.py", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/click/core.py", line 782, in main\n    rv = self.invoke(ctx)\n  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/click/core.py", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/click/core.py", line 610, in invoke\n    return callback(*args, **kwargs)\n  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/papermill/cli.py", line 238, in papermill\n    execution_timeout=execution_timeout,\n  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/papermill/execute.py", line 110, in execute_notebook\n    raise_for_execution_errors(nb, output_path)\n  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/papermill/execute.py", line 222, in raise_for_execution_errors\n    raise error\npapermill.exceptions.PapermillExecutionError: \n---------------------------------------------------------------------------\nException encountered at "In [1]":\n---------------------------------------------------------------------------\nFileExistsError                           Traceback (most recent call last)\n<ipython-input-1-e517ff5eec72> in <module>\n      7 os.getenv("OUTPUT_FILENAMES")\n      8 # Execute the node\n----> 9 NotebookNode().run()\n\n~/notebooks/elyra/pipeline1/node_util/node_util.py in run(self)\n     71         self.process_inputs("INPUT_FILENAMES")\n     72         self.perform_experiment()\n---> 73         self.process_outputs("OUTPUT_FILENAMES")\n     74 \n     75     def perform_experiment(self) -> None:\n\n~/notebooks/elyra/pipeline1/node_util/node_util.py in process_outputs(self, env_var)\n    104         for filename in filenames:\n    105             if filename:\n--> 106                 outputs.append(OutputNodeFile(filename))\n    107 \n    108 \n\n~/notebooks/elyra/pipeline1/node_util/node_util.py in __init__(self, filename)\n     36 \n     37         if os.path.exists(self.filename):\n---> 38             raise FileExistsError("File \'{}\' already exists!".format(self.filename))\n     39 \n     40     def write(self, data) -> None:\n\nFileExistsError: File \'node1a.out\' already exists!\n\n'`

By making these changes, we can get the contextual error back to the user, but, it's nasty.  If we add this, we should perhaps look into expanding the escaped newlines so that least this section of the error details reads more nicely - like what the logs show.

By the way when `capture_output=True` the log file would only contain _what we log_ and not the non-escaped output that is there today.  So, while we gain the information getting to the user, we lose the pretty-printing from the papermill logging.  That said, I think if we can pretty the `CalledProcessError.stderr` output (perhaps in the server so that the logged exception looks good as well) then this is probably a win for the user.

Thoughts?

cc: @lresende

**Comment by kevin-bates** [comment] 2020-10-04 15:37
Turns out that by simply decoding the `stderr` property as follows: `ex.stderr.decode('unicode_escape')` we can produce the following error details entry (which also gets logged into the server log the same way):

```
Traceback (most recent call last):
  File "/Users/kbates/repos/oss/elyra-ai/elyra/elyra/pipeline/processor_local.py", line 151, in process
    completed = run(argv, cwd=file_dir, env=envs, capture_output=True, check=True)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['papermill', '/Users/kbates/notebooks/elyra/pipeline1/node1.ipynb', '/Users/kbates/notebooks/elyra/pipeline1/node1.ipynb', '--cwd', '/Users/kbates/notebooks/elyra/pipeline1', '--no-progress-bar']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kbates/repos/oss/elyra-ai/elyra/elyra/pipeline/processor_local.py", line 70, in process
    operation_processor.process(operation)
  File "/Users/kbates/repos/oss/elyra-ai/elyra/elyra/pipeline/processor_local.py", line 153, in process
    raise RuntimeError(f'Internal error executing {filepath}: {ex.stderr.decode("unicode_escape")}') from ex
RuntimeError: Internal error executing /Users/kbates/notebooks/elyra/pipeline1/node1.ipynb: Input Notebook:  /Users/kbates/notebooks/elyra/pipeline1/node1.ipynb
Output Notebook: /Users/kbates/notebooks/elyra/pipeline1/node1.ipynb
Working directory: /Users/kbates/notebooks/elyra/pipeline1
Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-dev/bin/papermill", line 10, in <module>
    sys.exit(papermill())
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/papermill/cli.py", line 238, in papermill
    execution_timeout=execution_timeout,
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/papermill/execute.py", line 110, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/papermill/execute.py", line 222, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [1]":
---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
<ipython-input-1-e517ff5eec72> in <module>
      7 os.getenv("OUTPUT_FILENAMES")
      8 # Execute the node
----> 9 NotebookNode().run()

~/notebooks/elyra/pipeline1/node_util/node_util.py in run(self)
     71         self.process_inputs("INPUT_FILENAMES")
     72         self.perform_experiment()
---> 73         self.process_outputs("OUTPUT_FILENAMES")
     74 
     75     def perform_experiment(self) -> None:

~/notebooks/elyra/pipeline1/node_util/node_util.py in process_outputs(self, env_var)
    104         for filename in filenames:
    105             if filename:
--> 106                 outputs.append(OutputNodeFile(filename))
    107 
    108 

~/notebooks/elyra/pipeline1/node_util/node_util.py in __init__(self, filename)
     36 
     37         if os.path.exists(self.filename):
---> 38             raise FileExistsError("File '{}' already exists!".format(self.filename))
     39 
     40     def write(self, data) -> None:

FileExistsError: File 'node1a.out' already exists!



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/Users/kbates/repos/oss/elyra-ai/elyra/elyra/pipeline/handlers.py", line 89, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/Users/kbates/repos/oss/elyra-ai/elyra/elyra/pipeline/processor.py", line 69, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kbates/repos/oss/elyra-ai/elyra/elyra/pipeline/processor_local.py", line 72, in process
    raise RuntimeError(f'Error processing operation {operation.name}.') from ex
RuntimeError: Error processing operation node1.
```
I think this is an improvement and am happy to submit a PR if others agree.

**Comment by kevin-bates** [comment] 2020-10-04 20:07
I went ahead and created the PR since its probably easier to discuss this stuff in the PR.

**Comment by ptitzler** [comment] 2020-10-05 03:10
Much better, although I admit if the output in the "Error making request" dialog window could be reduced to just stating something like "An error occurred processing cell X in notebook Y. Please check the notebook output for details." that be (user friendly)^2 😃

**Closed** 2020-10-06 03:39 UTC
Labels: area:back-end, component:pipeline-runtime, component:troubleshooting
