### ISSUE TITLE
"No such file or directory" error when deploying a nonlocally created pipeline

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#608] opened 2020-06-05 08:46 UTC
If I check out a pipeline and try to run it on KFP I get the error below since the path

> /Users/romeokienzler/Documents/proj/1codait/corona/analysis/covid-notebooks/covid-notebooks/notebooks

is not valid but

> /Users/romeokienzler/Documents/proj/1codait/corona/analysis/covid-notebooks/notebooks

is. Note that the pipeline file resides in 

> /Users/romeokienzler/Documents/proj/1codait/corona/analysis/covid-notebooks/pipelines

Ways to reproduce
1. git clone https://github.com/CODAIT/covid-notebooks.git
2. cd covid-notebooks
3. jupyter-lab
4. In browser, open pipelines/eu_data.pipeline and try to run

> Traceback (most recent call last):
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 147, in process
>     kfp.compiler.Compiler().compile(cc_pipeline, pipeline_path)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 879, in compile
>     package_path=package_path)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 941, in _create_and_write_workflow
>     pipeline_conf)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 785, in _create_workflow
>     pipeline_func(*args_list)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 121, in cc_pipeline
>     dependency_archive_path = self._generate_dependency_archive(operation)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 196, in _generate_dependency_archive
>     recursive=operation.recursive_dependencies)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/elyra/util/archive.py", line 80, in create_temp_archive
>     tar.add(source_dir, arcname="", filter=tar_filter)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/tarfile.py", line 1928, in add
>     tarinfo = self.gettarinfo(name, arcname)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/tarfile.py", line 1807, in gettarinfo
>     statres = os.lstat(name)
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/romeokienzler/Documents/proj/1codait/corona/analysis/covid-notebooks/covid-notebooks/notebooks'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
>     result = method(*self.path_args, **self.path_kwargs)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/elyra/scheduler/handler.py", line 39, in post
>     run_url = PipelineProcessorManager.process(pipeline)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 59, in process
>     return processor.process(pipeline)
>   File "/Users/romeokienzler/opt/anaconda3/envs/tf2.0/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 152, in process
>     format(pipeline_name, pipeline_path), str(ex))
> RuntimeError: ('Error compiling pipeline romeotest-0605103914 at /var/folders/95/7hxgmrh92z91hylbxw647jhr0000gn/T/tmp0ejxy3vi/romeotest-0605103914.tar.gz', "[Errno 2] No such file or directory: '/Users/romeokienzler/Documents/proj/1codait/corona/analysis/covid-notebooks/covid-notebooks/notebooks'")

**Comment by kevin-bates** [comment] 2020-08-04 22:17
@romeokienzler - I'm unable to reproduce the issue using your steps above.  Using the steps above the attempted run produces the following:
![image](https://user-images.githubusercontent.com/22599560/89349503-20e1d980-d663-11ea-932c-58f4d6e843dc.png)
This is because all of the notebooks persisted in the covid-notebooks repo are relative to the covid-notebooks directory (which is the root directory for lab when invoked from that directory).  However, if I were to start `jupyter lab` either above or below `covid-notebooks`, then I see the issue.  I just wanted to make sure you're seeing the same thing. I'm wondering if you were using a version prior to [this commit](https://github.com/CODAIT/covid-notebooks/commit/41c54427c21b92a188f185c3a7dc49dacb7471ca#diff-b7675f5aabe650f0b233aacfd0f1e268) since it changed the relative references to each notebook in the pipeline.  At any rate, there's definitely an issue here.

When running from the parent directory of `covid-notebooks` - which is `/private/tmp` on my system - I get the following:
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 223, in _cc_pipeline
    dependency_archive_path = self._generate_dependency_archive(operation)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 284, in _generate_dependency_archive
    require_complete=True)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/util/archive.py", line 119, in create_temp_archive
    tar.add(source_dir, arcname="", filter=tar_filter)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/tarfile.py", line 1928, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/tarfile.py", line 1807, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/notebooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 59, in process
    kfp.compiler.Compiler().compile(pipeline_function, pipeline_path)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 926, in compile
    allow_telemetry=allow_telemetry)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 983, in _create_and_write_workflow
    allow_telemetry)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 806, in _create_workflow
    pipeline_func(*args_list)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 57, in <lambda>
    pipeline_function = lambda: self._cc_pipeline(pipeline, pipeline_name)  # nopep8 E731
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 241, in _cc_pipeline
    format(operation.name, ex))
FileNotFoundError: Node 'etl_us_data' referenced dependencies that were not found: [Errno 2] No such file or directory: '/private/tmp/notebooks'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 89, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 70, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 65, in process
    format(pipeline_name, pipeline_path), str(ex)) from ex
RuntimeError: ('Error compiling pipeline issue_608_2-0804150407 at /var/folders/4w/qxgsbhyx1y93qlk9mnzwjryc0000gn/T/tmpq_5xvli6/issue_608_2-0804150407.tar.gz', "Node 'etl_us_data' referenced dependencies that were not found: [Errno 2] No such file or directory: '/private/tmp/notebooks'")
```

**Comment by romeokienzler** [comment] 2020-08-06 10:34
@kevin-bates @ajbozarth I can confirm that the error is dependent on the location of the notebook file. So I can get it running if I place them correctly. This means if I use the ElyraAi function to clone a repo like [CovidNotebooks](https://github.com/CODAIT/covid-notebooks) I first have to manually move the files one layer up. So for me the issue is resolved with some minor UX glitches.

**Comment by kevin-bates** [comment] 2020-08-06 14:07
Hi @romeokienzler - this is a usability issue that we believe should be addressed.  Our current plan is to adjust the relationship of the notebook nodes to be relative to the pipeline file rather than the _notebook workspace_.  Therefore, I'm going to reopen this for now.  Should that decision change, we can always close it again.

FWIW - we did update the docs with [this section](https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html#distributing-your-pipeline) just yesterday.

**Comment by romeokienzler** [comment] 2020-08-18 09:16
I guess it the resources are relative to the pipeline file ux would be better

**Closed** 2020-08-20 17:10 UTC
Labels: area:back-end, area:front-end, kind:bug, kind:user-feedback, status:Needs Discussion
