### ISSUE TITLE
Add pipeline level env variables

### ISSUE THREAD

**Issue by blublinsky** [elyra-ai/elyra#1904] opened 2021-07-12 21:47 UTC
**Is your feature request related to a problem? Please describe.**
As described here https://github.com/kubeflow/kfp-tekton/tree/master/sdk#big-data-passing-workspace-configuration, some of the pipeline generation behaviour is defined by env variable, for example:

````
export DEFAULT_ACCESSMODES=ReadWriteMany
export DEFAULT_STORAGE_SIZE=2Gi
````` 
These should be added not to the individual components, but rather to a pipeline as a whole.
At the moment this is not supported.

**Comment by ptitzler** [comment] 2021-07-12 22:00
Duplicate of https://github.com/elyra-ai/elyra/issues/1843

**Closed by ptitzler** 2021-07-12 22:00 UTC
Labels: component:pipeline-editor, component:pipeline-runtime, duplicate, kind:enhancement

**Comment by lresende** [comment] 2021-07-12 22:02
Sorry @blublinsky, I didn't notice the other one for the env vars.
