### ISSUE TITLE
Support pipeline versions on KFP

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1114] opened 2020-11-25 20:55 UTC
Currently if one runs the same pipeline multiple times Elyra creates multiple pipelines in KFP as shown below:

![image](https://user-images.githubusercontent.com/13068832/100280253-b4922b00-2f1c-11eb-9bad-b2c301a1a4ef.png)

More recent versions of the KFP client support upload of pipeline versions, which Elyra should take advantage of.

For the example scenario above the result would be a single KFP pipeline `analyze_NOAA_weather_data`, which includes two versions. Just like it is done today for pipeline names, version identifiers could be generated on the fly.

**Comment by lresende** [comment] 2020-11-25 21:28
Duplicate of #679

**Closed** 2020-11-25 21:28 UTC
Labels: component:pipeline-runtime, duplicate, kind:enhancement
