### ISSUE TITLE
KFP pipeline run link does not work if the KFP API endpoint ends with "/"

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1605] opened 2021-04-22 19:55 UTC
**Describe the issue**
I believe this is a regression

**To Reproduce**
1. Create A KFP RTC, specifying a KFP endpoint that ends in "/", e.g. `http://cloning99.fyre.ibm.com:12345/pipeline/`
2. Create a notebook
3. Create a pipeline
4. add the notebook
5. run pipeline
6. click the "Run details" link in the submission confirmation dialog

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**
Should link to 
```
http://cloning99.fyre.ibm.com:12345/pipeline/#/runs/details/ae3e8a95-22e6-4542-81ea-4efe4668269e
```
instead of 
```
http://cloning99.fyre.ibm.com:12345/pipeline//#/runs/details/ae3e8a95-22e6-4542-81ea-4efe4668269e
```

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.2.2+
 - Installation source: from source
 - Deployment type: local installation

**Comment by kevin-bates** [comment] 2021-04-22 20:44
> I believe this is a regression

Looks like this was only explicitly done for git integration: https://github.com/elyra-ai/elyra/pull/1363

**Comment by kevin-bates** [comment] 2021-04-22 22:09
We realized in the sync-up today, that this _could_ be a regression that had previously been fixed in the frontend and re-introduced with the pipeline 2.0 changes.  We'll be sure to address this in the server via this time.

Question: Should _any_ url-valued properties have a trailing slash?  If not, this could probably be handled generically when the metadata is persisted.

**Comment by ptitzler** [comment] 2021-04-22 22:32
> Question: Should any url-valued properties have a trailing slash? If not, this could probably be handled generically when the metadata is persisted.

Not sure there is one answer that is correct 100% of the time.

**Closed** 2021-05-29 03:51 UTC
Labels: component:pipeline-runtime, kind:bug, status:Needs Triage
