### ISSUE TITLE
Environment without Kubeflow

### ISSUE THREAD

**Issue by SebastienDorgan** [elyra-ai/elyra#2922] opened 2022-09-10 11:34 UTC
**Is your feature request related to a problem? Please describe.**
I have created an environment with Airflow installed, I do not plan to use Kubeflow, is there a way to not install Kubeflow Pipeline editor and Kubeflow configuration extension?

**Describe the solution you'd like**
Maybe it could be useful to create 3 distincts pipeline editor extensions package
[https://elyra.readthedocs.io/en/v2.1.0/getting_started/installation.html#pip](https://elyra.readthedocs.io/en/v2.1.0/getting_started/installation.html#pip)

- pip install --upgrade elyra-airflow-pipeline-editor-extension && jupyter lab build
- pip install --upgrade elyra-generic-pipeline-editor-extension && jupyter lab build
- pip install --upgrade elyra-kubeflow-pipeline-editor-extension && jupyter lab build

**Describe alternatives you've considered**
Adding the possibility to deactivate the extension from Jupyter lab configuration

**Comment by ptitzler** [comment] 2022-09-12 05:41
Related PR https://github.com/elyra-ai/elyra/pull/2259

**Comment by lresende** [comment] 2022-09-12 14:58
Duplicate of #2136

**Closed by lresende** 2022-09-12 14:58 UTC
Labels: kind:enhancement, component:pipeline-editor, component:pipeline-runtime, status:Needs Triage, component:install
