### ISSUE TITLE
start using prebuilt JupyterLab extensions (reduce install time)

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2339] opened 2021-12-02 22:52 UTC
Currently, we are using [source extensions](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#source-extensions) rather than [prebuilt extensions](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions) for Jupyterlab, you can read about the differences [here](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#overview-of-extensions).

The gist of the problem is that it can take an __incredible__ amount of time to install Elyra right now, as you have to run `jupyter lab build`, and then restart JupyterLab. If we moved to prebuilt extensions, installing would be as simple as `pip install elyra`.

**Comment by ajbozarth** [comment] 2021-12-03 17:08
This is a duplicate of #1077 which has a abandoned draft PR #1850

I plan to start/continue work on this starting today with a target for v3.4

**Closed** 2022-02-25 18:50 UTC
Labels: kind:enhancement, component:install
