### ISSUE TITLE
Pipeline node properties does not recognize new environment variables

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#710] opened 2020-07-06 20:56 UTC
Create a notebook with some environment variables in a cell:

```
print(os.getenv('USER', default_value))
print(os.getenv('LOGNAME', default_value))
```

Add node to the pipeline and then go to node properties

![image](https://user-images.githubusercontent.com/382917/86641482-0519e380-bf90-11ea-8ec4-f811b9574200.png)

Add more environment variables to the same or another cell:

```
print(os.getenv('USER', default_value))
print(os.getenv('LOGNAME', default_value))
print(os.getenv('CONDA_DEFAULT_ENV', default_value))
```

Save the notebook, reopen the pipeline and the node properties

![image](https://user-images.githubusercontent.com/382917/86641774-3eeaea00-bf90-11ea-9756-7ce98e7516d5.png)

No changes, this is because we are reading/parsing the env_vars values during node add.

This should be fixed by implementing #957 and then integrating on the UI.

**Comment by ajbozarth** [comment] 2020-07-06 21:09
This was by design (not to say it shouldn't be updated to be better). Originally users had to add all the env vars themselves. We then updated it to its current state where it will populate an initial set of env vars when adding a notebook node to a pipeline. 

To address this shortcoming we could move our "initialization" code from node creation to when properties is opened. This would require comparing the list of env vars against the current value of the "vars" node property so as to add new env vars, but not duplicate or delete current one's who's value may have already been set. This has the potential to scale poorly since in order to grab the env vars in a notebook, the notebook is parsed, which might not be "instant" for very large notebooks.

**Comment by kevin-bates** [comment] 2020-07-06 21:22
It might be helpful to store a "last-parsed" timestamp as part of the pipeline or properties metadata (client-side only) and compare that timestamp < notebook last-modified timestamp, then only re-parse if the notebook has been modified since properties were last opened.

**Comment by lresende** [comment] 2020-07-06 23:05
Also, we should always keep an eye on `submitting notebook` versus `pipelines` as they have similar semantics and dialogs but completely different implementations, and this is one behavioral difference.

**Comment by kevin-bates** [comment] 2020-07-07 00:58
> we should always keep an eye on submitting notebook versus pipelines as they have similar semantics and dialogs but completely different implementations, and this is one behavioral difference.

I'm not sure this needs to be treated as a difference.  If I follow what the differences are between Notebook and Pipeline submission, I view the former as a strict subset of the latter.  If NB submission parses the notebook for envs, shouldn't pipeline submission do the same for each node (or vice versa) at time of submission?  Isn't NB submission just a pipeline submission of one node (with no inputs/outputs, just dependencies)?

Yes, pipelines have this open-the-node-dialog that NB submission doesn't, but we still to parse the notebook at time of submission, so the extra stuff for pipelines is why they are considered a superset of NB.

I apologize if my understanding is not correct.

**Comment by lresende** [comment] 2020-07-07 18:47
@kevin-bates you are correct. The implementation does not resonate this today because they were originally created as two distinct extensions without the ability to share code. Now that we managed to merge them as one extension, we should cleanup the implementation.

**Comment by kevin-bates** [comment] 2020-07-07 19:21
Ah - okay - thank you for the explanation.

**Comment by karlaspuldaro** [comment] 2021-03-01 23:17
This should also get addressed in the `Submit Script` feature added by #1330

**Comment by akchinSTC** [comment] 2021-03-18 16:57
@rasyab66 - Hi there! just checking in to see if any progress has been made on this issue, the reason being is that there is currently work being done in #385 that might conflict with yours here.

**Comment by rasyab66** [comment] 2021-03-22 23:33
> @rasyab66 - Hi there! just checking in to see if any progress has been made on this issue, the reason being is that there is currently work being done in #385 that might conflict with yours here.

Hi! I have not made significant progress on the issue as of now.

**Comment by akchinSTC** [comment] 2021-04-13 22:55
how will the environment variable parser be called in new pipeline editor ?
see https://github.com/elyra-ai/elyra/pull/1221

**Comment by ajbozarth** [comment] 2021-04-13 23:46
@akchinSTC I've put my work here on hold until after that PR is merged so I'll reevaluate it once that happens

**Closed** 2021-05-20 16:09 UTC
Labels: component:pipeline-editor, good first issue, help wanted, kind:user-feedback, program:RCOS, stretch
