### ISSUE TITLE
Add ability to add custom Kubeflow components to pallete

### ISSUE THREAD

**Issue by blublinsky** [elyra-ai/elyra#1905] opened 2021-07-12 21:53 UTC
**Is your feature request related to a problem? Please describe.**

At the moment there is no support for adding custom kubeflow components  through the editor UI. It would be nice to add this support

**Comment by ptitzler** [comment] 2021-07-12 21:57
Duplicate of https://github.com/elyra-ai/elyra/issues/1880. Refer to https://github.com/elyra-ai/elyra/discussions/1881 for a temporary manual solution.

**Closed by ptitzler** 2021-07-12 21:57 UTC
Labels: kind:enhancement, status:Needs Triage
