### ISSUE TITLE
[NIT] Difficult to locate common properties button when using dark mode

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1381] opened 2021-03-08 21:22 UTC
**Describe the issue**
In dark mode - hard to see three dots in node to open common props when not highlighted

**To Reproduce**
0. Activate dark mode,
1. Go to pipeline editor, drag a notebook to create a node
2. Scroll over the node and highlight the 3 dots.

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/13340013/110383814-aff80b00-8011-11eb-852c-ba036d46f5b5.png)

![image](https://user-images.githubusercontent.com/13340013/110383423-14ff3100-8011-11eb-9c1f-7696e75bcca7.png)

If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**
3 dots visible when cursor not over the 3 dots

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.0 rc1
 - Operating system: macos
 - Installation source: pypi 
 - Deployment type: local

**Comment by sabary661990615** [comment] 2021-06-07 02:57
I believe I have thought of a possible solution to this problem that would also create a long term benefit for Elyra design and customizability. I have used an open source text editor that had its own seperate GitHub where uses could push and pull different themes for the application. I believe implementing something similar for Elyra while also fixing this issue in the base dark mode would be extremely beneficial. Let me know if you think this is a good idea.

**Comment by karlaspuldaro** [comment] 2021-06-07 18:49
Hi @sabary661990615 , thank you for the feedback.

There are a few theme packages that can be installed by the user as Jupyterlab extensions, like [jupyterlab-themes](https://github.com/arbennett/jupyterlab-themes)
 and [dracula](https://github.com/dracula/jupyterlab). Only not sure how well they work with the pipeline editor since it's built on [canvas](https://github.com/elyra-ai/canvas), unlike other editors in Elyra that simply extend Jupyterlab ones.
And that is also why this issue is Elyra specific, even though the dark mode theme code lives in [Jupyterlab repo](https://github.com/jupyterlab/jupyterlab/tree/master/packages/theme-dark-extension), we just need to make some adjustments on our side. I can assign you to this issue and help you find the files to work on.

Then if you're interested in building new Jupyterlab themes, which is awesome btw, I would suggest having its own extension repo or in collaboration with the existing ones, but that's just my opinion :) Feel free to propose your idea as a new issue so we can keep future discussions around it separate from the scope of this one.

**Comment by karlaspuldaro** [comment] 2021-06-15 18:13
Closing this as it's no longer reproducible.  This is how the nodes look like now with the most recent pipeline updates:
![image](https://user-images.githubusercontent.com/25207344/122102657-a980e880-cde3-11eb-87ed-8a37eae72d49.png)

**Closed by karlaspuldaro** 2021-06-15 18:13 UTC
Labels: component:pipeline-editor, component:pipeline-runtime, good first issue, kind:user-feedback
