### ISSUE TITLE
Pipeline migration produces invalid container image reference in pipeline file

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2208] opened 2021-10-07 19:36 UTC
**Describe the issue**

Currently we have two hooks touching the same value (runtime image) which are expected to occur sequentially, but are actually triggered separately by changes to the jupyterlab widget content and the canvas content respectively. In theory this should be the same, but is causing this race condition when only the widget detects changes but the canvas does not.

**To Reproduce**
1. Clone https://github.com/elyra-ai/examples
2. Open [`examples/pipelines/dax_noaa_weather_data/analyze_NOAA_weather_data.pipeline`](https://github.com/elyra-ai/examples/blob/master/pipelines/dax_noaa_weather_data/analyze_NOAA_weather_data.pipeline) in a text editor and review all `runtime_image` property values:
    ```
    "runtime_image": "docker.io/amancevice/pandas:1.1.1"
    ```
2. Open [`examples/pipelines/dax_noaa_weather_data/analyze_NOAA_weather_data.pipeline`](https://github.com/elyra-ai/examples/blob/master/pipelines/dax_noaa_weather_data/analyze_NOAA_weather_data.pipeline) in the VPE
3. The migration wizard opens. Migrate the pipeline.
4. Save the pipeline and close the pipeline editor.
5. Open the pipeline file again in a text editor and review the `runtime_image` property values:
   ```
   "runtime_image": "Pandas 1.1.1"
   ```

   Note that the updated values are not valid container image names.
6. Try to run the pipeline. It fails because there is no image with such a name.

**Expected behavior**

The two hooks content should either not be dependent on each other or we should make sure one hook triggers the next if that behavior is expected.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.2/rc0

**Comment by ajbozarth** [comment] 2021-10-07 20:00
I've done some initial digging into the code and this seems to stem from  #1671 and possibly #1882 and has been in place since 3.0

IIUC this will still work if using only the VPE since it converts it to the correct format at submission. But it makes the persisted pipeline incompatible with the CLI.

I'm continuing to look into this and figure out the solution

**Comment by ajbozarth** [comment] 2021-10-08 21:26
Ok after some serious digging I've traced this down to a race condition with two of our onChange hooks.

 One hook is tied to changes to the content of the editor (ie any change via jupyterlab) and sets the value to the display_name so it renders in the dropdown correctly. The other hook changes it back to the actual image value and is tied to various common canvas on change hooks (ie any change via canvas). 

In this case the hook for handling a migration triggers the first hook, but doesn't trigger the second hook until save, but if you save using the jupyterlab functionality (ie control+S or clicking close and getting the unsaved prompt) the canvas doesn't always see a change and trigger the second hook.

I believe this is just a symptom of issues with our callbacks and should be addressed by improving those rather than fixing this one use case. This was previously discussed as a problem when working on #1924

FYI the hooks in question are https://github.com/elyra-ai/elyra/blob/6e7ebf5c78914edac53483cde21bf8300419337a/packages/pipeline-editor/src/PipelineEditorWidget.tsx#L218 which is triggered in the migration hook at https://github.com/elyra-ai/elyra/blob/6e7ebf5c78914edac53483cde21bf8300419337a/packages/pipeline-editor/src/PipelineEditorWidget.tsx#L346 and sets the values to the display name. And https://github.com/elyra-ai/elyra/blob/6e7ebf5c78914edac53483cde21bf8300419337a/packages/pipeline-editor/src/PipelineEditorWidget.tsx#L274 which is handed to common canvas and is triggered by edits to the pipeline or any properties.

**Comment by lresende** [comment] 2021-10-08 22:33
> I believe this is just a symptom of issues with our callbacks and should be addressed by improving those rather than fixing this one use case. This was previously discussed as a problem when working on #1924

Well, how often this problem is reproducible? If often, this is a blocking issue as it would prevent the pipeline to run and should be fixed ASAP. Possibly by a workaround first, then a rework of the callbacks as you described.

**Comment by ajbozarth** [comment] 2021-10-14 22:53
I tracked down the issue and opened #2231 with a fix. The actual bug is described in detail there

**Closed** 2021-10-17 10:07 UTC
Labels: kind:bug, component:pipeline-editor
