### ISSUE TITLE
Initial properties view doesn't expand image selection drop down to full width

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1450] opened 2021-03-17 15:09 UTC
**Describe the issue**
Initial properties view doesn't expand image selection drop down to full width

**To Reproduce**
Drag a notebook to the canvas and open the properties

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/5694071/111490050-fc8ec500-873a-11eb-9279-26df3f4416a8.png)

**Expected behavior**
Drop down has full width

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.0rc5
 - Operating system: [rhel 7.9]
 - Installation source: [dev docker image]
 - Deployment type: [e.g. local docker installation]
 - Browser: FF 85.0.2

**Comment by akchinSTC** [comment] 2021-03-17 16:09
@ajbozarth - is this related to #1442 and the new canvas version as well?

**Comment by romeokienzler** [comment] 2021-03-17 16:32
@akchinSTC I confirm that at least the behavior in #1442 is exactly the same - so this here is most likely a duplicate issue

**Comment by ptitzler** [comment] 2021-03-17 16:40
If you want to build your own version of the container image then the change discussed here https://github.com/elyra-ai/elyra/issues/1442#issuecomment-801137389 should resolve the problem if it's indeed caused by the later canvas version.

**Comment by akchinSTC** [comment] 2021-03-17 20:22
@romeokienzler - in the interest of keeping organized, I'm going to close this issue as a duplicate of #1442 and we can move any conversations over to that thread.

**Closed by akchinSTC** 2021-03-17 20:22 UTC
Labels: component:pipeline-editor, component:pipeline-runtime, kind:user-feedback, status:Needs Triage

**Comment by romeokienzler** [comment] 2021-03-17 20:43
sure, thanks a lot! @akchinSTC
