### ISSUE TITLE
Can not launch after installing elyra

### ISSUE THREAD

**Issue by yarnabrina** [elyra-ai/elyra#3070] opened 2023-01-09 16:17 UTC
**Describe the issue**
I installed elyra in a fresh new environment, and then tried to launch Jupyter Lab. It led to `ModuleNotFoundError: No module named 'jsonschema.protocols'`.

**To Reproduce**
1. Create a new python virtual environment.
  - tried with `conda`, `micromamba`, `venv`
  - tried with `3.9`, `3.10`, `3.11`
2. Activate the virtual environment.
3. Install `elyra` with `pip install elyra`.
4. Start Jupyter Lab with `jupyter lab`.
5. See error

**Screenshots or log output**

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/39331844/211352400-b05e7d94-5cbe-45a7-b5a3-a59a2d69c0dc.png">

<details><summary>Log Output</summary>
<pre>
(py311) root@test:/# jupyter lab
Traceback (most recent call last):
  File "/opt/conda/envs/py311/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterlab/labapp.py", line 13, in <module>
    from jupyter_server.serverapp import flags
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 33, in <module>
    from jupyter_events.logger import EventLogger
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyter_events/__init__.py", line 2, in <module>
    from .logger import EVENTS_METADATA_VERSION, EventLogger
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyter_events/logger.py", line 18, in <module>
    from .schema_registry import SchemaRegistry
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyter_events/schema_registry.py", line 3, in <module>
    from .schema import EventSchema
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyter_events/schema.py", line 6, in <module>
    from jsonschema.protocols import Validator
ModuleNotFoundError: No module named 'jsonschema.protocols'
</pre>
</details>

**Expected behavior**
Jupyter lab opens without any issue.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.14.1
 - Installation source: PyPI
 - Deployment type: local installation
 - Operating system: `macos`, `condaforge/miniforge3:latest`

**Note**
This can possibly be some upstream error, but installing just `jupyterlab` worked fine, so that's why it seemed to be caused by `elyra` only.

**Comment by kevin-bates** [comment] 2023-01-09 21:31
Hi @yarnabrina - this is indeed an upstream issue with `jupyter_events` that finds itself "in the weeds" fairly quickly due to `kfp`'s (possibly artificial) cap on `jsonschema < 4`.  This is why you don't see the issue by only installing `jupyterlab` (which pulls in `jupyter_events` via `jupyter_server`).  The Jupyter Server team (of which I'm a member) is working on addressing this in `jupyter_events` so that `jsonschema < 4` dependencies can be honored.  Until then, we'll need to keep this open, then probably update our floor of `jupyter_events` to the corresponding patch release.

**Comment by kevin-bates** [comment] 2023-01-09 21:45
@yarnabrina - could you please include the output of `pip freeze` from the env in which this is occurring?

**Comment by kevin-bates** [comment] 2023-01-09 22:11
@yarnabrina - you might try working around this issue via `pip install "jsonschema[format_nongpl]==4.3.0"`. You should get warnings resembling the following, of which only the one related to `kfp` is meaningful since the second is self-imposed due to the first.
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kfp 1.8.18 requires jsonschema<4,>=3.0.1, but you have jsonschema 4.3.0 which is incompatible.
elyra 3.14.1 requires jsonschema<4.0,>=3.2.0, but you have jsonschema 4.3.0 which is incompatible.
```

I suspect the `kfp` cap is more preventative than anything else, but haven't confirmed if using `jsonschema == 4.3.0` interferes with client-side activity triggered via elyra or not.  If you're using `kfp`, it would helpful if you could report back any experiences you have (both good or bad) and we'll use that as a datapoint moving forward since this all can be resolved by removing that cap.

**Comment by kevin-bates** [comment] 2023-01-09 22:28
FWIW - [this comment](https://github.com/kubeflow/pipelines/issues/8648#issuecomment-1373941029) appears to indicate the `kfp` cap is artificial.  Hoping they'll provide a patch release that would enable us to move forward more gracefully.

**Comment by yarnabrina** [comment] 2023-01-10 10:04
> @yarnabrina - could you please include the output of `pip freeze` from the env in which this is occurring?

<details><summary>Output of `pip freeze`</summary>
<pre>
absl-py==1.3.0
ansiwrap==0.8.4
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
astroid==2.13.2
asttokens==2.2.1
attrs==22.2.0
autopep8==1.6.0
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.1
black==22.12.0
bleach==5.0.1
cachetools==5.2.1
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
cloudpickle==2.2.0
colorama==0.4.6
comm==0.1.2
debugpy==1.6.5
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.13
deprecation==2.1.0
dill==0.3.6
docstring-parser==0.15
docstring-to-markdown==0.11
elyra==3.14.1
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.2
fire==0.5.0
flake8==6.0.0
gitdb==4.0.10
GitPython==3.1.30
google-api-core==2.11.0
google-api-python-client==1.12.11
google-auth==2.16.0
google-auth-httplib2==0.1.0
google-cloud-core==2.3.2
google-cloud-storage==2.7.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.58.0
httplib2==0.21.0
idna==3.4
ipykernel==6.20.1
ipython==8.8.0
ipython-genutils==0.2.0
isort==5.11.4
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.11
jsonschema==3.2.0
jupyter-events==0.4.0
jupyter-lsp==1.5.1
jupyter-resource-usage==0.7.0
jupyter-server-mathjax==0.2.6
jupyter_client==7.4.8
jupyter_core==4.12.0
jupyter_packaging==0.12.3
jupyter_server==2.0.6
jupyter_server_terminals==0.4.4
jupyterlab==3.5.2
jupyterlab-git==0.41.0
jupyterlab-lsp==3.10.2
jupyterlab-pygments==0.2.2
jupyterlab_server==2.16.6
kfp==1.8.18
kfp-pipeline-spec==0.1.17
kfp-server-api==1.8.5
kubernetes==19.15.0
lazy-object-proxy==1.9.0
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mccabe==0.7.0
minio==7.1.13
mistune==2.0.4
mypy-extensions==0.4.3
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.7
nbdime==3.1.1
nbformat==5.7.1
nest-asyncio==1.5.6
networkx==3.0
notebook==6.5.2
notebook_shim==0.2.2
oauthlib==3.2.2
packaging==23.0
pandocfilters==1.5.0
papermill==2.4.0
parso==0.8.3
pathspec==0.10.3
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.6.2
pluggy==1.0.0
prometheus-client==0.15.0
prompt-toolkit==3.0.36
protobuf==3.20.3
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.10.0
pycparser==2.21
pydantic==1.10.4
pydocstyle==6.2.3
pyflakes==3.0.1
PyGithub==1.57
Pygments==2.14.0
PyJWT==2.6.0
pylint==2.15.10
PyNaCl==1.5.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.4
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.7.0
pytoolconfig==1.2.4
pytz==2022.7
PyYAML==5.4.1
pyzmq==24.0.1
requests==2.28.1
requests-oauthlib==1.3.1
requests-toolbelt==0.10.1
rfc3986-validator==0.1.1
rope==1.6.0
rsa==4.9
Send2Trash==1.8.0
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
snowballstemmer==2.2.0
soupsieve==2.3.2.post1
stack-data==0.6.2
strip-hints==0.1.10
tabulate==0.9.0
tenacity==8.1.0
termcolor==2.2.0
terminado==0.17.1
textwrap3==0.9.2
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.6
tornado==6.2
tqdm==4.64.1
traitlets==5.8.1
typer==0.7.0
typing_extensions==4.4.0
ujson==5.7.0
uritemplate==3.0.1
urllib3==1.26.13
watchdog==2.2.1
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.2
whatthepatch==1.0.3
wrapt==1.14.1
yapf==0.32.0
yaspin==2.3.0
</pre>
</details>

**Closed** 2023-01-11 00:55 UTC
Labels: external:Upstream
